// ── Posts ─────────────────────────────────────────────────
export type PostType = 'ARTICLE' | 'RESEARCH_PAPER' | 'IPR_DOCUMENT';
export type PostStatus = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED';
export type AiStatus = 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED';

export interface Post {
  id: string;
  title: string;
  slug: string;
  excerpt?: string;
  content: string;
  summary?: string;            // AI-generated by Claude Haiku 4.5
  imageUrl?: string;           // Cloudinary URL — cover image
  documentUrl?: string;        // PDF URL for research papers / IPR docs
  postType: PostType;
  status: PostStatus;
  aiProcessingStatus: AiStatus;
  views: number;
  isPinned: boolean;
  categories: Category[];
  tags: Tag[];
  createdAt: string;
  updatedAt: string;
  publishedAt?: string;
}

// ── Categories & Tags ─────────────────────────────────────
export interface Category {
  id: string;
  name: string;
}

export interface Tag {
  id: string;
  name: string;
}

// ── Comments ──────────────────────────────────────────────
export interface Comment {
  id: string;
  postId: string;
  parentId?: string;
  guestName: string;       // e.g. "Guest_83920471" — assigned by backend
  content: string;
  isApproved: boolean;
  createdAt: string;
}

// ── Newsletter ────────────────────────────────────────────
export interface SubscribeRequest {
  email: string;
}

export interface SubscribeResponse {
  message: string;
}

// ── API wrappers ──────────────────────────────────────────
export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}

// ── Nav ───────────────────────────────────────────────────
export interface NavItem {
  label: string;
  path: string;
  icon?: React.ReactNode;
}